export const GAME_CONFIG = {
  // Значение WIN_THRESHOLD должно быть в диапазоне от POWER_MIN до POWER_MAX
  WIN_THRESHOLD: 60,
  POWER_MIN: 0,
  POWER_MAX: 100,
}

export const POWER_RANGE = GAME_CONFIG.POWER_MAX - GAME_CONFIG.POWER_MIN

export const POWER_CONFIG = {
  MIN: GAME_CONFIG.POWER_MIN,
  MAX: GAME_CONFIG.POWER_MAX,
  RANGE: POWER_RANGE,
  SPEED: 200,
  REDIRECT_CHANCE: 0.015,
}
